%package -n patterns-sailfish-device-configuration-f5321
Summary: Jolla Configuration f5321
Requires: patterns-sailfish-device-configuration-common-f5321
Requires: patterns-sailfish-device-adaptation-kugo

Requires: droid-config-f5321-sailfish
Requires: droid-config-f5321-pulseaudio-settings
Requires: droid-config-f5321-policy-settings
Requires: droid-config-f5321-preinit-plugin
Requires: droid-config-f5321-flashing
Requires: droid-config-f5321-bluez5
Requires: droid-hal-version-f5321

Requires: patterns-sailfish-cellular-apps

Requires: sailfish-content-graphics-z%{icon_res}

# jolla-settings-system-nfc
Requires: jolla-settings-system-flashlight

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

Requires: patterns-sailfish-consumer-generic
Requires: patterns-sailfish-device-tools

%description -n patterns-sailfish-device-configuration-f5321
Pattern with packages for f5321 configurations

%files -n patterns-sailfish-device-configuration-f5321
