%package -n patterns-sailfish-device-configuration-kugo
Summary: Jolla Configuration kugo
Requires: patterns-sailfish-device-configuration-common-kugo
Requires: patterns-sailfish-device-adaptation-kugo

Requires: droid-config-kugo-sailfish
Requires: droid-config-kugo-pulseaudio-settings
Requires: droid-config-kugo-policy-settings
Requires: droid-config-kugo-preinit-plugin
Requires: droid-config-kugo-flashing
Requires: droid-config-kugo-bluez5
Requires: droid-hal-version-kugo

Requires: patterns-sailfish-cellular-apps

Requires: sailfish-content-graphics-z%{icon_res}

# jolla-settings-system-nfc
Requires: jolla-settings-system-flashlight

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

Requires: patterns-sailfish-consumer-generic
Requires: patterns-sailfish-device-tools

%description -n patterns-sailfish-device-configuration-kugo
Pattern with packages for kugo configurations

%files -n patterns-sailfish-device-configuration-kugo
