%package -n patterns-sailfish-device-configuration-f5121
Summary: Jolla Configuration f5121
Requires: patterns-sailfish-device-configuration-common-f5121
Requires: patterns-sailfish-device-adaptation-suzu

Requires: droid-config-f5121-sailfish
Requires: droid-config-f5121-pulseaudio-settings
Requires: droid-config-f5121-policy-settings
Requires: droid-config-f5121-preinit-plugin
Requires: droid-config-f5121-flashing
Requires: droid-config-f5121-bluez5
Requires: droid-hal-version-f5121

Requires: patterns-sailfish-cellular-apps

Requires: sailfish-content-graphics-z%{icon_res}

# jolla-settings-system-nfc
Requires: jolla-settings-system-flashlight

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

Requires: patterns-sailfish-consumer-generic
Requires: patterns-sailfish-device-tools

%description -n patterns-sailfish-device-configuration-f5121
Pattern with packages for f5121 configurations

%files -n patterns-sailfish-device-configuration-f5121
